### ISSUE TITLE
你好，这个导入项目用不了。。

### ISSUE THREAD

**Issue by boai** [a1anyip/AYVibrantButton#15]
- (void)setCornerRadius:(CGFloat)cornerRadius {
	_cornerRadius = cornerRadius;
	[self.buttons.firstObject setCornerRadius:cornerRadius];
	[self.buttons.lastObject setCornerRadius:cornerRadius];
}
在这里会报错！

**Comment by a1anyip** [comment]
What is the error message?

**Comment by boai** [comment]
忘了，好久了。。。下次在遇到我给你贴出来！
