### ISSUE TITLE
Button disappears as soon as UITableViewCell is selected

### ISSUE THREAD

**Issue by CooperRS** [a1anyip/AYVibrantButton#7]
Hello,

I added a AYVibrantButton to the contentView of a UITableViewCell. As soon as I tap that cell the button disappears and appears again when the cell is deselected. Any ideas on that?

Best regards,
Roland

**Comment by kartikthapar** [comment]
@a1anyip @Evildime  Can you please merge this?

**Comment by a1anyip** [comment]
Thanks for the commit. I have changed `backgroundColor` to `tintColor` instead of `highlightColor`, with some deprecated warnings in 1.0.4 as well.
